import Head from "next/head";
import Image from "next/image";
import { useEffect, useState } from "react";

import styled from "styled-components";

export default function Home() {
	const [starships, setStarships] = useState([]);
	const [loading, setLoading] = useState(true);
	const [error, setError] = useState(null);
	useEffect(() => {
		getStarships();
	}, []);

	const getStarships = async () => {
		try {
			const res = await Promise.all([
				fetch("https://swapi.dev/api/starships"),
				fetch("https://swapi.dev/api/starships/?page=2"),
				fetch("https://swapi.dev/api/starships/?page=3"),
				fetch("https://swapi.dev/api/starships/?page=4"),
			]);

			let successResponses = [];
			let errorResponses = [];
			console.log(res);

			res.map((r) => {
				if (r.ok) {
					successResponses.push(r);
				} else {
					errorResponses.push(r);
				}
			});

			console.log(errorResponses);
			if (errorResponses.length > 0) {
				getMoreStarships(successResponses);
			} else {
				const data = await Promise.all(res.map((r) => r.json()));
				formatStarshipResponse(data);
			}
		} catch (error) {
			return null;
		}
	};

	const getMoreStarships = async (successResponses) => {
		const arrayOfResponses = await Promise.all(
			successResponses.map((url) =>
				fetch(url.url).then((res) => res.json())
			)
		);
		formatStarshipResponse(arrayOfResponses);
	};

	const formatStarshipResponse = (data) => {
		const testing = data.map((r) => {
			return r.results;
		});
		const merge = testing.flat(1);

		const formattedStarships = merge.filter(
			(starship) => starship.crew <= 10
		);
		console.log(formattedStarships);
		formattedStarships.sort((a, b) => parseFloat(a.crew) - parseFloat(b.crew));
		setLoading(false);
		setStarships(formattedStarships);
	};

	return loading ? (
		<p>Loading</p>
	) : (
		<ContainerStyles>
			<Head>
				<title>Star Wars Ships</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main >
				<div className="intro">
					<h1 >Welcome to Star Wars Ships!</h1>

				</div>
				<div className="shipContainer">
					{starships.map((starship) => (
						<div key={starship.name} className="ship">
							<h2>{starship.name}</h2>
							<p>Model: {starship.model}</p>
							<p>Manufacturer: {starship.manufacturer}</p>
							<p>Crew: {starship.crew}</p>
							<p>Films: {starship.films.length}</p>
						</div>
					))}

				</div>
			</main>
		</ContainerStyles>
	);
}

const ContainerStyles = styled.div`
	display: flex;
	justify-content: center;
	text-align: center;
	background-image: url("../img/stars.jpg");
	background-size: cover;
	background-repeat: no-repeat;
	background-position: center;
	padding: 4rem;
	main {
		.intro {
			color: white;
		}
		.shipContainer {
			max-width: 1200px;
			display: grid;
			grid-template-columns: repeat(4, 1fr);
			gap: 1rem;
			.ship {
				background: white;
				border-radius: 10px;

			}
		}
	}
`;
